export const paths = {
  home: "/",
  adminDashboard: "/admin/dashboard",
  practitionerDashboard: "/practitioner/dashboard",
  signup: "/organisation-signup",
  login: "/login",
  forgotPassword: "/forgot-password",
  otpverify: "/otp-verify",
  resetPassword: "/reset-password",
  successPassword: "/success-password",
  paymentConfirmation: "/payment-confirmation",
  subscription: "/admin/subscription",
  organisationSubscriptionRequired: "/organisation/subscription",
  subscriptionSuccess: "/subscription/success",
} as const;
